void search_sno()
{
 FILE *fp;
 int found,n;
 clrscr();
 textcolor(WHITE);
 cprintf("Enter the serial number :");
 scanf("%d",&n);
 fp=fopen("info.dat","r");
 found=0;
 while(fread(&cont,sizeof(cont),1,fp)!=NULL)
	{
		if(cont.sno==n)
		{
			printf("\nCategory  : %s",cont.category);
			printf("\nName      : %s",cont.name);
			printf("\nGender    : %c",cont.gender);
			printf("\nAge       : %d",cont.age);
			printf("\nAddress   : %s",cont.address);
			printf("\nPhone     : %s",cont.phone);
			printf("\n--------------------------------------");
			found=1;
			break;
		}
	}
	if(found==0)
	{
	printf("Data Not Exist,Press Any Key to Return....");
	fclose(fp);
	getch();
	return;
	}
	fclose(fp);
	getch();
}
void search_category()
{	FILE *fp;
	char cat[20];
	window(1,1,80,25);
	textbackground(BLACK);
	textcolor(RED);
	clrscr();
	printf("Enter category :");
	gets(cat);
	gotoxy(34,1);
	printf("LIST OF CONTACTS");
	printf("\n");
	for(int i=1;i<=80;i++)
	printf("-");
	gotoxy(1,3);
	printf("SNO");
	gotoxy(8,3);
	printf("CATEGORY");
	gotoxy(20,3);
	printf("NAME");
	gotoxy(36,3);
	printf("GENDER");
	gotoxy(46,3);
	printf("AGE");
	gotoxy(55,3);
	printf("ADDRESS");
	gotoxy(70,3);
	printf("PHONE");

	printf("\n");
	for(i=1;i<=80;i++)
	printf("-");
	fp=fopen("info.dat","rb");
	i=5;
	while(fread(&cont,sizeof(cont),1,fp)!=NULL)
	{
	if(strcmpi(cat,cont.category)==0)
  {	gotoxy(1,i);
	printf("%d",cont.sno);
	gotoxy(8,i);
	printf("%s",cont.category);
	gotoxy(20,i);
	printf("%s",cont.name);
	gotoxy(36,i);
	printf("%c",cont.gender);
	gotoxy(46,i);
	printf("%d",cont.age);
	gotoxy(55,i);
	printf("%s",cont.address);
	gotoxy(70,i);
	printf("%s",cont.phone);
	i++;
	}
  }
	fclose(fp);
	textcolor(RED+BLINK);
	printf("\n");
	cprintf("Press Any Key...");
	getch();
	}

void search_name()
{	FILE *fp;
	char cat[20];
	window(1,1,80,25);
	textbackground(BLACK);
	textcolor(RED);
	clrscr();
	printf("Enter Name :");
	gets(cat);
	gotoxy(34,1);
	printf("LIST OF CONTACTS");
	printf("\n");
	for(int i=1;i<=80;i++)
	printf("-");
	gotoxy(1,3);
	printf("SNO");
	gotoxy(8,3);
	printf("CATEGORY");
	gotoxy(20,3);
	printf("NAME");
	gotoxy(36,3);
	printf("GENDER");
	gotoxy(46,3);
	printf("AGE");
	gotoxy(55,3);
	printf("ADDRESS");
	gotoxy(70,3);
	printf("PHONE");

	printf("\n");
	for(i=1;i<=80;i++)
	printf("-");
	fp=fopen("info.dat","rb");
	i=5;
	while(fread(&cont,sizeof(cont),1,fp)!=NULL)
	{
	if(strcmpi(cat,cont.name)==0)
  {	gotoxy(1,i);
	printf("%d",cont.sno);
	gotoxy(8,i);
	printf("%s",cont.category);
	gotoxy(20,i);
	printf("%s",cont.name);
	gotoxy(36,i);
	printf("%c",cont.gender);
	gotoxy(46,i);
	printf("%d",cont.age);
	gotoxy(55,i);
	printf("%s",cont.address);
	gotoxy(70,i);
	printf("%s",cont.phone);
	i++;
	}
  }
	fclose(fp);
	textcolor(RED+BLINK);
	printf("\n");
	cprintf("Press Any Key...");
	getch();
	}

void search_phone()
{ FILE *fp;
 int found;
 char ph[15];
 clrscr();
 textcolor(WHITE);
 cprintf("Enter the phone number :");
 gets(ph);
 fp=fopen("info.dat","r");
 found=0;
 while(fread(&cont,sizeof(cont),1,fp)!=NULL)
	{
		if(strcmp(ph,cont.phone)==0)
		{
			printf("\nCategory  : %s",cont.category);
			printf("\nName      : %s",cont.name);
			printf("\nGender    : %c",cont.gender);
			printf("\nAge       : %d",cont.age);
			printf("\nAddress   : %s",cont.address);
			printf("\nPhone     : %s",cont.phone);
			printf("\n--------------------------------------");
			found=1;
			break;
		}
	}
	if(found==0)
	{
	printf("Data Not Exist,Press Any Key to Return....");
	fclose(fp);
	getch();
	return;
	}
	fclose(fp);
	getch();
}

